server {
    listen 80;
    server_name localhost;

    # Gelen istekleri dinler ve karşılığını arar
    location / {
        # Statik dosyaların bulunduğu kök dizin (Dockerfile'da buraya kopyaladık)
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # SPA (Vue Router) Yönlendirmesi:
        # Nginx, istenen dosyayı bulamazsa 404 vermek yerine 'index.html'i yükler.
        # Böylece yönlendirme işlemini (routing) arka planda Vue kendisi yapar.
        try_files $uri $uri/ /index.html;
    }

    # Sunucu kaynaklı bir hata olursa varsayılan hata sayfasını gösterir
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
